### ISSUE TITLE
ArmCord not working on Hyprland/NVIDIA

### ISSUE THREAD

**Issue by D3vil0p3r** [smartfrigde/armcord#413]
**Describe the bug**
ArmCord does not start correctly on Hyprland. I have a NVIDIA GPU. I run ArmCord by:
```
armcord --enable-features=WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform-hint=auto
```
it opens the window but the Discord icon rotates forever and the application never shows the login form.

The terminal shows the following logs:
```
[Config manager] doneSetup: false
[Config manager] performanceMode: none
First run of the ArmCord. Starting setup.
Setting up temporary ArmCord settings.
No performance modes set
[Config manager] windowStyle: default

(electron:1502763): Gtk-WARNING **: 01:20:13.676: Theme parsing error: gtk.css:6691:68: Invalid name of pseudo-class
[Config manager] armcordCSP: true
[Config manager] doneSetup: false
[Config manager] customIcon: /usr/share/armcord/app.asar/assets/desktop.png
Setting up CSP unstricter...
[Config manager] trayIcon: default
[Config manager] customIcon: /usr/share/armcord/app.asar/assets/desktop.png
[Config manager] tray: true
[Config manager] skipSplash: false
[Config manager] clientName: ArmCord
[Config manager] windowStyle: default
[Config manager] mods: none
[Mod loader] Skipping
(node:1502763) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/athena/.config/ArmCord/storage/window.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:469:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at getWindowState (/usr/share/armcord/app.asar/ts-out/utils.js:245:22)
    at createCustomWindow (/usr/share/armcord/app.asar/ts-out/window.js:296:50)
    at init (/usr/share/armcord/app.asar/ts-out/main.js:88:53)
    at async /usr/share/armcord/app.asar/ts-out/main.js:103:9
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:1502763) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[1502763:0623/012013.763651:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
WebContents #1 called ipcRenderer.sendSync() with 'modInstallState' channel without listeners.
WebContents #1 called ipcRenderer.sendSync() with 'get-app-version' channel without listeners.
Error occurred in handler for 'getLang': Error: No handler registered for 'getLang'
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:88973)
    at EventEmitter.emit (node:events:513:28)
```

**To Reproduce**
1. On an Hyprland environment run `armcord --enable-features=WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform-hint=auto`
2. Wait

**Expected behavior**
ArmCord opening correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux latest
 - Method of installation: AUR package
 - Version r878.a531d4e-1 

**Additional context**

**Comment by smartfrigde** [comment]
Are you using -git version? If, so please try the stabler armcord-bin package?

**Comment by D3vil0p3r** [comment]
I'm using the -git version. The bin package works well. Btw the -git version does not work only at the first run, because if I remove -git version, then I install bin package, run it, then close the application and reinstall -git version and run `armcord`, it works without going to the rolling discord icon window, but it goes directly to the login window, so I think that the -git issue could occur either at the first run or when an update is available.

UPDATE: if I reboot, `armcord-git` continues to not work.

**Comment by smartfrigde** [comment]
fixed in latest commit
