### ISSUE TITLE
Black screen on startup

### ISSUE THREAD

**Issue by redyf** [smartfrigde/armcord#419]
**Describe the bug**
Armcord displays a black screen every time I open it, I can't even complete the initial setup.

**To Reproduce**
Run ArmCord.

**Expected behavior**
Discord login screen.

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/98139059/4d23169e-97b2-4ce9-9bb3-807373ffa66f)

**Desktop (please complete the following information):**
 - OS: NixOS (Linux).
 - Method of installation: Nixpkgs.
 - Version: 3.2.0.

**Additional context**
I've tried to reinstall but didn't work, I'm using hyprland on NixOS btw.

**Comment by smartfrigde** [comment]
send terminal output here

**Comment by ErynGalen** [comment]
When starting ArmCord, at first the window stays black, with this output:
```
[Config manager] doneSetup: true
[Config manager] performanceMode: none
ArmCord has been run before. Skipping setup.
No performance modes set
[Config manager] windowStyle: default
[7986:0715/111109.789110:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[7986:0715/111109.789290:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
[Config manager] armcordCSP: true
[Config manager] doneSetup: true
[Config manager] customIcon: undefined
Setting up CSP unstricter...
[Config manager] trayIcon: ac_white_plug
[Config manager] skipSplash: false
[Config manager] trayIcon: ac_white_plug
[Config manager] windowStyle: default
[Config manager] tray: true
[Config manager] clientName: undefined
[Config manager] mods: none
[Mod loader] Skipping
(node:7986) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token '^@', "^@^@^@^@^@^@^@^@^@^@"... is not valid JSON
    at JSON.parse (<anonymous>)
    at getWindowState (/usr/share/armcord/app.asar/ts-out/utils.js:249:27)
    at createCustomWindow (/usr/share/armcord/app.asar/ts-out/window.js:295:50)
    at init (/usr/share/armcord/app.asar/ts-out/main.js:98:53)
    at async /usr/share/armcord/app.asar/ts-out/main.js:113:9
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:7986) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
WebContents #1 called ipcRenderer.sendSync() with 'modInstallState' channel without listeners.
[8065:0715/111114.264582:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[8065:0715/111114.279278:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[8065:0715/111123.704134:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```
(I've replaced null characters by `^@`.)

After some time the animation with the rotating discord logo starts, and ArmCord hangs there, with this additionnal output:
```
WebContents #1 called ipcRenderer.sendSync() with 'get-app-version' channel without listeners.
Error occurred in handler for 'getLang': Error: No handler registered for 'getLang'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88989)
    at WebContents.emit (node:events:513:28)

```

**Comment by smartfrigde** [comment]
Set `~/.config/ArmCord/storage/window.json` to `{}`

**Comment by ErynGalen** [comment]
Actually, only removing the file fixed it.
EDIT: No, I had just made a typo :/.
