### ISSUE TITLE
ArmCord has broken JSON input, not allowing for it to start

### ISSUE THREAD

**Issue by zastrixarundell** [smartfrigde/armcord#464]
**Describe the bug**
Installed ArmCord via the flatpak. Every installation lasted for around ~1 week before getting a certain JSON input error, After that error there's no way to fix it unless the flatpak data is removed and flatpak is run again (personally I only did `flatpak uninstall xyz.armcord.Armcord --delete-data && flatpak install xyz.armcord.ArmCord`)

**To Reproduce**
1. Use the ArmCord flatpak
2. Randomly get the IO error
3. Not be able to run ArmCord

**Expected behavior**
ArmCord would launch

**Logs**
```
$ flatpak run xyz.armcord.ArmCord --trace-warnings
Using Wayland, enabling PipeWire for video capture.
Screenshare may be broken on first start.
Make sure you have the legacy screencapturer enabled.
Wayland socket not available, running through Xwayland.
Using NVIDIA on Wayland, applying workaround
Passing the following arguments to Electron: --enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --disable-gpu-blocklist --disable-gpu-sandbox --enable-features=UseSkiaRenderer,WebRTCPipeWireCapturer,WebRTCPipeWireCapturer
[3:0914/094632.314971:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Wayland detected, using PipeWire for video capture.
[Config manager] doneSetup: true
[Config manager] performanceMode: none
ArmCord has been run before. Skipping setup.
No performance modes set
[Config manager] windowStyle: default
Gtk-Message: 09:46:32.481: Failed to load module "colorreload-gtk-module"
Gtk-Message: 09:46:32.481: Failed to load module "window-decorations-gtk-module"
[3:0914/094632.495062:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0914/094632.495093:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[Config manager] armcordCSP: true
[Config manager] doneSetup: true
[Config manager] customIcon: /app/bin/armcord/resources/app.asar/assets/desktop.png
Setting up CSP unstricter...
[Config manager] trayIcon: default
[Config manager] customIcon: /app/bin/armcord/resources/app.asar/assets/desktop.png
[Config manager] tray: true
[Config manager] skipSplash: false
[Config manager] clientName: ArmCord
[Config manager] windowStyle: default
[Config manager] mods: vencord
[Config manager] noBundleUpdates: undefined
Downloading mod bundle
[Config manager] mods: vencord
https://github.com/Vendicated/Vencord/releases/download/devbuild/browser.js
[Mod loader] Loaded ArmCord Mod Loader made by Vendicated
(node:3) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getWindowState (/app/bin/armcord/resources/app.asar/ts-out/utils.js:249:27)
    at createCustomWindow (/app/bin/armcord/resources/app.asar/ts-out/window.js:309:50)
    at init (/app/bin/armcord/resources/app.asar/ts-out/main.js:91:53)
    at async /app/bin/armcord/resources/app.asar/ts-out/main.js:106:9
    at emitUnhandledRejectionWarning (node:internal/process/promises:200:15)
    at processPromiseRejections (node:internal/process/promises:296:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:3) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getWindowState (/app/bin/armcord/resources/app.asar/ts-out/utils.js:249:27)
    at createCustomWindow (/app/bin/armcord/resources/app.asar/ts-out/window.js:309:50)
    at init (/app/bin/armcord/resources/app.asar/ts-out/main.js:91:53)
    at async /app/bin/armcord/resources/app.asar/ts-out/main.js:106:9
src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

# This logs below will show 30 seconds after the previous log 

WebContents #1 called ipcRenderer.sendSync() with 'modInstallState' channel without listeners.
WebContents #1 called ipcRenderer.sendSync() with 'get-app-version' channel without listeners.
Error occurred in handler for 'getLang': Error: No handler registered for 'getLang'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89431)
    at WebContents.emit (node:events:513:28)
```

**Screenshots**
https://github.com/ArmCord/ArmCord/assets/30195425/6f070c39-d60d-47eb-b306-0612c3123d8b

**Desktop (please complete the following information):**
 - OS: Fedora Kinoite 38 (ostree-image-signed:docker://ghcr.io/ublue-os/kinoite-nvidia:38-530)
 - Method of installation: flatpak
 - Version: 
 ```
 $ flatpak list | awk '/^ArmCord/ { print $3 }'
3.2.4
```

**Comment by smartfrigde** [comment]
Might be fixed with https://github.com/ArmCord/ArmCord/commit/b1f876de7c8d20b6f0f74bdf037cfd2eef955acf? From now on when a config is corrupted ArmCord should reset the config, and start the initial setup again.

**Comment by zastrixarundell** [comment]
Are you sure that's the best way to do it, as in resetting the config file? I'm not sure which data is in it but if it's my personal configuration I really wouldn't like to have to setup ArmCord every week and to describe it as "working".

Wouldn't it be more appropriate to see and patch the JSON file or to make the config changes thread-safe?

**Comment by tr1p0p** [comment]
Yeah it still a thing, and suddently for no reason armcord refuse to launch, when it worked perfectly like yesterday.

...Maybe there's a reason why discord team don't put the *last* electron build on their program ? Because for me it doesn't seem stable **at all**

**Comment by tr1p0p** [comment]
> Might be fixed with [b1f876d](https://github.com/ArmCord/ArmCord/commit/b1f876de7c8d20b6f0f74bdf037cfd2eef955acf)? From now on when a config is corrupted ArmCord should reset the config, and start the initial setup again.

This is absolutely not what armcord do. Why this program is in unstable state ? Can i do something because i just... can't go to discord now ?

**Comment by DodoLeDev** [comment]
I've had the same error, and when digging into where the source of the problem might be, I've found a file: `~/.config/ArmCord/storage/window.json`.
It's goal seems to be to store the last window state. This is consistent with the fact that your error is triggered by a `getWindowState` method.

However, when I faced your error, **the file was empty**! And this seems to throw errors.

### The solution
Delete the empty `~/.config/ArmCord/storage/window.json` file, then restart ArmCord.
It worked for me, and I hope it'll work for you too!

**Comment by zastrixarundell** [comment]
@DodoLeDev hm that's interesting. I'll use armcord until I get this error and then see to test it out. Wayland doesn't generally support where the application was last run (I mean the compositor does but not the app (I have super limited knowledge)) so this might be the reason why it doesn't work. 

This is also a config which isn't really a problem to have removed, it's just window placement, it's not like the whole config needs to be reset.

**Comment by RoseIlanga** [comment]
The workaround worked for me too. I should add that I'm having this issue on X11 though.

**Comment by DodoLeDev** [comment]
> The workaround worked for me too. I should add that I'm having this issue on X11 though.

It seems that the problem is compositor-independent.

---

To fix this issue, I suggest to simply handle errors like these, and delete faulty files when thrown.

**Comment by RoseIlanga** [comment]
If it's any help, I recall WebCord having a similar issue with a blank window state file: https://github.com/SpacingBat3/WebCord/issues/360

**Comment by zastrixarundell** [comment]
It's definitely window state which is making an issue. I think that the [file write operation](https://github.com/ArmCord/ArmCord/blob/19d02f69defc76878e9ea43b294de70636980dea/src/utils.ts#L224C14-L224C14) is not writing the file correctly. In most cases I saw on StackOverflow on why this is happening is due to the call being async. It is sync here but maybe in some scenarios the parent function is called in a matter where it's not synced? I did see await keywords but I'm not a node-js dev to figure it out properly.

We *could* perform a data check [here](https://github.com/ArmCord/ArmCord/blob/19d02f69defc76878e9ea43b294de70636980dea/src/utils.ts#L233C12-L233C12) on the read value, for sure but it'd be better to fix the cause of the issue, not the symptom of it. 

Edit: Eh it might be a good idea to do both honestly. In case the system managed to force-close armcord in the exact same moment while the file is being written. It'd just be bad practice to fix the symptom only.

**Comment by smartfrigde** [comment]
https://github.com/Legcord/Legcord/releases/tag/v1.2.0
