### ISSUE TITLE
Armcord fails to connect to bus, causing it to be unable to start

### ISSUE THREAD

**Issue by PercyPanleo** [smartfrigde/armcord#472]
Armcord fails to start, only being shown as a background program

When running it through the terminal with logging enabled I get the following:

`$ flatpak run xyz.armcord.ArmCord --trace-warnings
Using Wayland, enabling PipeWire for video capture.
Screenshare may be broken on first start.
Make sure you have the legacy screencapturer enabled.
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --disable-gpu-blocklist --ozone-platform=wayland --enable-features=UseSkiaRenderer,WebRTCPipeWireCapturer,WebRTCPipeWireCapturer
[3:0929/124014.673050:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Wayland detected, using PipeWire for video capture.
[Config manager] doneSetup: true
[Config manager] performanceMode: performance
ArmCord has been run before. Skipping setup.
Performance mode enabled
[Config manager] windowStyle: native
[3:0929/124014.908495:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0929/124014.908536:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[Config manager] armcordCSP: true
[Config manager] doneSetup: true
[Config manager] customIcon: undefined
Setting up CSP unstricter...
[Config manager] trayIcon: default
[Config manager] skipSplash: true
[Config manager] tray: false
[Config manager] windowStyle: native
[Config manager] tray: false
[Config manager] mods: vencord
[Config manager] noBundleUpdates: undefined
Downloading mod bundle
[Config manager] mods: vencord
https://github.com/Vendicated/Vencord/releases/download/devbuild/browser.js
[Mod loader] Loaded ArmCord Mod Loader made by Vendicated
(node:3) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getWindowState (/app/bin/armcord/resources/app.asar/ts-out/utils.js:249:27)
    at createNativeWindow (/app/bin/armcord/resources/app.asar/ts-out/window.js:332:50)
    at init (/app/bin/armcord/resources/app.asar/ts-out/main.js:95:53)
    at async /app/bin/armcord/resources/app.asar/ts-out/main.js:106:9
    at emitUnhandledRejectionWarning (node:internal/process/promises:200:15)
    at processPromiseRejections (node:internal/process/promises:296:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:3) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getWindowState (/app/bin/armcord/resources/app.asar/ts-out/utils.js:249:27)
    at createNativeWindow (/app/bin/armcord/resources/app.asar/ts-out/window.js:332:50)
    at init (/app/bin/armcord/resources/app.asar/ts-out/main.js:95:53)
    at async /app/bin/armcord/resources/app.asar/ts-out/main.js:106:9`

This issue happened seemingly at random, so I don't know how to reproduce this issue, but after the first occurrence it's happened every time I've attempted to start Armcord since.
I can't seem to find a solution to this problem as reinstalling the app didn't help and attempting to clear the data when uninstalling gave `error: No installed refs found for ‘xyz.armcord.Armcord’`

My PC is running Fedora Workstation 38 with GNOME 44.5 under Wayland on kernel version 6.5.5-200

**Comment by PercyPanleo** [comment]
Update: Got around the clear data issue, still doesn't start

**Comment by PercyPanleo** [comment]
As it turns out, this issue is the same as #464 
However, in my case the empty window.json was stored at `~/.var/app/xyz.armcord.ArmCord/config/ArmCord/storage` rather than `~/.config/ArmCord/storage`
