### ISSUE TITLE
Armcord opens and charges infinitely

### ISSUE THREAD

**Issue by Heus-Sueh** [smartfrigde/armcord#508]
**Armcord opens and charges infinitely**

```
❯ flatpak run xyz.armcord.ArmCord
Using Wayland, enabling PipeWire for video capture.
Screenshare may be broken on first start.
Make sure you have the legacy screencapturer enabled.
Wayland socket not available, running through Xwayland.
Using NVIDIA on Wayland, applying workaround
Passing the following arguments to Electron: --enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --disable-gpu-blocklist --disable-gpu-sandbox --enable-features=UseSkiaRenderer,WebRTCPipeWireCapturer,WebRTCPipeWireCapturer
[3:1112/130237.495280:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Wayland detected, using PipeWire for video capture.
[Config manager] doneSetup: true
[Config manager] performanceMode: performance
ArmCord has been run before. Skipping setup.
Performance mode enabled
[Config manager] windowStyle: native
Gtk-Message: 13:02:37.712: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:02:37.712: Failed to load module "canberra-gtk-module"
[3:1112/130237.735594:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1112/130237.735648:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[Config manager] armcordCSP: true
[Config manager] doneSetup: true
[Config manager] customIcon: undefined
Setting up CSP unstricter...
[Config manager] trayIcon: ac_plug_colored
[Config manager] skipSplash: false
[Config manager] trayIcon: ac_plug_colored
[Config manager] windowStyle: native
[Config manager] tray: true
[Config manager] clientName: undefined
[Config manager] mods: vencord
[Config manager] noBundleUpdates: undefined
Downloading mod bundle
[Config manager] mods: vencord
https://github.com/Vendicated/Vencord/releases/download/devbuild/browser.js
[Mod loader] Loaded ArmCord Mod Loader made by Vendicated
(node:3) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getWindowState (/app/bin/armcord/resources/app.asar/ts-out/utils.js:249:27)
    at createNativeWindow (/app/bin/armcord/resources/app.asar/ts-out/window.js:332:50)
    at init (/app/bin/armcord/resources/app.asar/ts-out/main.js:95:53)
    at async /app/bin/armcord/resources/app.asar/ts-out/main.js:106:9
(Use `armcord --trace-warnings ...` to show where the warning was created)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 538982482

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 943215175

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094158

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 842094169

src/gbm_drv_common.c:57: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

WebContents #1 called ipcRenderer.sendSync() with 'modInstallState' channel without listeners.
WebContents #1 called ipcRenderer.sendSync() with 'get-app-version' channel without listeners.
Error occurred in handler for 'getLang': Error: No handler registered for 'getLang'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88753)
    at WebContents.emit (node:events:514:28)
```

**To Reproduce**
try to open the armcord

**Expected behavior**
open

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue + Nvidia
 - Method of installation: Flatpak
 - Version: 3.2.5

**Additional context**

**Comment by Heus-Sueh** [comment]
The solution was to completely delete it and install it again
