### ISSUE TITLE
ArmCord error on M1

### ISSUE THREAD

**Issue by phibluu** [smartfrigde/armcord#62]
hi, I'm on an m1 and since there's no official arm64 for macos build, I attempted to build from source. In the process after running npm i, then attempting to start using npm start. I get a very large error and ArmCord fails to start:

> ArmCord@2.5.0 start
> electron .

/Users/phillip/ArmCord/node_modules/electron/index.js:17
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again');
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/Users/phillip/ArmCord/node_modules/electron/index.js:17:11)
    at Object.<anonymous> (/Users/phillip/ArmCord/node_modules/electron/index.js:21:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/phillip/ArmCord/node_modules/electron/cli.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

 I'm not very familiar with javascript so I would appreciate any help, thanks.

**Comment by smartfrigde** [comment]
`npm run package` or `npm run make` should work. Just as a note ArmCord wasn't tested on mac os and I've seen reports of it being broken there. I have no access to any apple device so I can't fix it :(
You can always try though.
