### ISSUE TITLE
Vencord does not load when starting Legcord normally

### ISSUE THREAD

**Issue by creeper82** [smartfrigde/armcord#763]
**Describe the bug**
Once in a few startups, Vencord does not load, until I reload with the keyboard shortcut.

It is different from all similar issues, as it happens during a clean start, and not just a restart. I have no idea what might cause it. I remember having the same issue before the app rebrand, but somehow it started working, and now after a fresh install it happens again

**To Reproduce**
1. Simply open the app

**Expected behavior**
Vencord should be loaded

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Method of installation: aur
 - Version: 1.0.2

**Comment by CryptisMidnight** [comment]
I am also getting this on both Vencord and Equicord

- OS: openSUSE Tumbleweed
- Method of installation: downloaded and installed .rpm
- Version: 1.0.2

**Comment by AndroAGENT** [comment]
i got the same thing and not just with opening, it's also when the app isn't in the focus for a long time
- OS: Windows 11 Pro
- Method of installation: Microsoft Store
- Version: 1.0.2

**Comment by lammersbjorn** [comment]
Having the same issue with Vencord & Equicord.

- OS: MacOS 15.0.1 (24A348)
- Method of installation: Homebrew (Tried installing from GitHub release as well with the same result)
- Version: 1.0.2

Console logs:
```
preload.mjs:20 Custom bundle failed to load!
(anonymous) @ preload.mjs:20

preload.mjs:20 TypeError: Cannot read properties of undefined (reading 'enabled')
    at preload.mjs:20:103
    at async preload.mjs:20:52
(anonymous) @ preload.mjs:20

preload.mjs:20 Equicord Failed to load!
(anonymous) @ preload.mjs:20

preload.mjs:20 TypeError: Error processing argument at index 0, conversion failure from undefined
    at preload.mjs:20:509
    at async preload.mjs:20:438
(anonymous) @ preload.mjs:20

preload.mjs:30 Legcord 1.0.2
```

**Comment by SomeAspy** [comment]
can you post your config file?

**Comment by lammersbjorn** [comment]
Using the default, fresh install.

```json
{
    "windowStyle": "default",
    "channel": "stable",
    "legcordCSP": true,
    "minimizeToTray": true,
    "keybinds": [],
    "audio": "loopbackWithMute",
    "multiInstance": false,
    "mods": [
        "equicord"
    ],
    "transparency": "none",
    "spellcheck": true,
    "hardwareAcceleration": true,
    "performanceMode": "none",
    "skipSplash": false,
    "inviteWebsocket": true,
    "startMinimized": false,
    "tray": false,
    "disableHttpCache": false,
    "customJsBundle": "https://legcord.app/placeholder.js",
    "customCssBundle": "https://legcord.app/placeholder.css",
    "disableAutogain": false,
    "useLegacyCapturer": false,
    "mobileMode": false,
    "trayIcon": "dynamic",
    "doneSetup": true,
    "clientName": "Legcord",
    "customIcon": "/Applications/Legcord.app/Contents/Resources/app.asar/assets/desktop.png",
    "smoothScroll": true,
    "autoScroll": false,
    "modCache": {
        "shelter": "6c4160f81cdb6daa253d6c767b94c26605ba86d1",
        "vencord": "5216bcca1eca1b79a5a397e2128414ef653daee7",
        "equicord": "91367e459822d09f50aac8191aeae17271a2c41c"
    }
}
```

**Comment by CryptisMidnight** [comment]
as a work around i did get it to load more regularly with disableHttpCache on/true, and clear client mod cache.
```json
{
    "windowStyle": "native",
    "channel": "stable",
    "legcordCSP": true,
    "minimizeToTray": false,
    "keybinds": [],
    "audio": "loopbackWithMute",
    "multiInstance": false,
    "mods": [
        "equicord"
    ],
    "transparency": "universal",
    "spellcheck": true,
    "hardwareAcceleration": true,
    "performanceMode": "performance",
    "skipSplash": true,
    "inviteWebsocket": true,
    "startMinimized": false,
    "tray": false,
    "disableHttpCache": true,
    "customJsBundle": "https://legcord.app/placeholder.js",
    "customCssBundle": "https://legcord.app/placeholder.css",
    "disableAutogain": false,
    "useLegacyCapturer": false,
    "mobileMode": false,
    "trayIcon": "dynamic",
    "doneSetup": true,
    "clientName": "Legcord",
    "customIcon": "/opt/Legcord/resources/app.asar/assets/desktop.png",
    "smoothScroll": true,
    "autoScroll": false,
    "modCache": {
        "shelter": "6c4160f81cdb6daa253d6c767b94c26605ba86d1",
        "vencord": "88e8fa7e904e525c4c1110d057f0812e4008ff7c",
        "equicord": "a16f241b856aa508dfbf2662984939bd6cbb8dde"
    }
}
```

**Comment by lammersbjorn** [comment]
> as a work around i did get it to load more regularly with disableHttpCache on/true, and clear client mod cache.

This seems to work about 50/50 when launching it a couple of times. Could it be ratelimiting?

**Comment by SomeAspy** [comment]
I thought the config is corrupted, I guess not. if you delete the cache data does it work? I'm just guessing as I am not at my desktop right now.
```json
    "modCache": {
        "shelter": "6c4160f81cdb6daa253d6c767b94c26605ba86d1",
        "vencord": "88e8fa7e904e525c4c1110d057f0812e4008ff7c",
        "equicord": "a16f241b856aa508dfbf2662984939bd6cbb8dde"
    }
```
I think there was a bug in the cache setup, but I will have to check later.

**Comment by lammersbjorn** [comment]
Deleting cache does seem to work. But it breaks again after re-launching a couple of times. Clearing cache again, fixes it.

**Comment by SomeAspy** [comment]
Yeah every time it runs, it will execute the code to grab the modloader. this includes checking the github API. however, iirc, if the github API returns a 401 or ratelimits you for whatever reason that (broken) response will be cached.
I'll have a look later. 
https://github.com/Legcord/Legcord/blob/dev/src/discord/extensions/modloader.ts#L42-L61

**Comment by SomeAspy** [comment]
Do you get a standard 200 response if you go to `https://api.github.com/repos/vendicated/vencord/git/matching-refs/heads/main`?
the data in the cache is actually the commit hash
![image](https://github.com/user-attachments/assets/24b47ee6-4dde-4600-8c10-55beed78b25c)

**Comment by lammersbjorn** [comment]
Yep.

```
[
  {
    "ref": "refs/heads/main",
    "node_id": "REF_kwDOH3-5sK9yZWZzL2hlYWRzL21haW4",
    "url": "https://api.github.com/repos/Vendicated/Vencord/git/refs/heads/main",
    "object": {
      "sha": "5216bcca1eca1b79a5a397e2128414ef653daee7",
      "type": "commit",
      "url": "https://api.github.com/repos/Vendicated/Vencord/git/commits/5216bcca1eca1b79a5a397e2128414ef653daee7"
    }
  }
]
```

**Comment by SomeAspy** [comment]
I've been asking myself if the cache is even worth having - the mods themselves are ~~only a few kilobytes maximum~~ less than 1mb, and checking the cache already makes requests. it might just be better to remove it, but I'm not sure.

**Comment by lammersbjorn** [comment]
Caching is always great as long as it works properly 😛

**Comment by SomeAspy** [comment]
regardless, I am struggling to re-create this bug locally, even after manually corrupting the cache data, perhaps the mod file itself is damaged. 
is the sha256sum of your `equicord.js` as follows? `2be799623eecb45ccc9f3933ffa26a02fc368f7b08106ddc1f5280b4d57ec5b7`
assuming the application is pulling the correct hash (at the time it should be
`"equicord": "91367e459822d09f50aac8191aeae17271a2c41c"`)
is the file even there?

**Comment by lammersbjorn** [comment]
Where would I find this file? It's not there :P

**Comment by SomeAspy** [comment]
On linux it should be `~/.config/legcord/equicord.js` or `vencord.js` if you are using vencord.
I'm not sure on MacOS - in relation to the settings.json it should be in the directory that the settings.json directory is in
(in relation to settings.json)
`../equicord.js`

**Comment by lammersbjorn** [comment]
Nope, not there.

**Comment by SomeAspy** [comment]
If its not there it's just plain not downloading.
based on your config, it looks like you are on MacOS, I will have to check this on my mac when I get home.
I have not tested specifically on MacOS, assuming it would just work cross-platform, but we have a windows, linux, and mac user in here so I'm really not sure? chances are you might all be having slightly different issues...

**Comment by SomeAspy** [comment]
> On linux it should be `~/.config/legcord/equicord.js` or `vencord.js` if you are using vencord. I'm not sure on MacOS - in relation to the settings.json it should be in the directory that the settings.json directory is in (in relation to settings.json) `../equicord.js`

@creeper82 can you confirm `equicord.js` is even there?

**Comment by SomeAspy** [comment]
@walkxcode I'm not able to replicate this issue on my 2020 M1 macbook with MacOS Sequoia, I installed via brew.

For me, the js files are in `~/Library/Application\ Support/legcord/` Can you check there? in the directory should be `{vencord|equicord}.{js|css}`

**Comment by ghost** [comment]
Same issue here, also Arch Linux through AUR and also clearing the cache works 50/50 of the time

**Comment by marcohefti** [comment]
Same problem on M1 Mac 14.6.1 (23G93). It's a fresh install done through homebrew. Logged in, enabled a bunch of plugins, restarted and since then Vencord is gone

```
[default] [BUILD INFO] Release Channel: ptb, Build Number: 343356, Version Hash: cff1a057a97c78b42bc31618fc27242cc891a7f4
web.e8580451dbad240e7a31.js:12 AppCrashedFatalReport: getLastCrash not supported.
preload.mjs:20 Custom bundle failed to load!
(anonymous) @ preload.mjs:20
Show 1 more frame
Show less
preload.mjs:20 TypeError: Cannot read properties of undefined (reading 'enabled')
    at preload.mjs:20:103
    at async preload.mjs:20:52
(anonymous) @ preload.mjs:20
Show 1 more frame
Show less
sentry.85dee49e633ff1076f4f.js:14 Failed to parse settings from localStorage:  TypeError: Cannot read properties of undefined (reading 'getItem')
    at Object.get (VencordWeb:236:1325)
    at VencordWeb:18:44863
    at VencordWeb:5:497
    at VencordWeb:25:6824
    at VencordWeb:5:497
    at VencordWeb:25:7117
    at VencordWeb:5:497
    at VencordWeb:227:42643
    at VencordWeb:5:497
    at VencordWeb:227:56330
    at VencordWeb:5:497
    at VencordWeb:227:56841
    at VencordWeb:5:497
    at VencordWeb:235:1961
    at VencordWeb:5:497
    at VencordWeb:236:1563
    at VencordWeb:236:1584
    at async preload.mjs:20:251
(anonymous) @ sentry.85dee49e633ff1076f4f.js:14
VencordWeb:18 Uncaught TypeError: Cannot set properties of undefined (setting 'Vencord_settingsDirty')
    at VencordWeb:18:45516
    at VencordWeb:18:2463
    at Set.forEach (<anonymous>)
    at Object.set (VencordWeb:18:2452)
    at VencordWeb:21:633
    at Array.forEach (<anonymous>)
    at VencordWeb:21:504
    at VencordWeb:5:497
    at VencordWeb:235:1971
    at VencordWeb:5:497
    at VencordWeb:236:1563
    at VencordWeb:236:1584
    at async preload.mjs:20:251
preload.mjs:20 Vencord Failed to load!
```

**Comment by marcohefti** [comment]
Deleting the cache in ```~/Library/Application Support/legcord/Cache/Cache_Data``` temporarily fixed the problem

**Comment by SomeAspy** [comment]
I just disabled the cache entirely - I'm just out of ideas right now, and just want it working

**Comment by andre1808** [comment]
I at first thought I have the same issue as so many here are experiencing. But just when I wanted to relaunch Legcord, I've had a Loading chunk 22721 failed error.
![image](https://github.com/user-attachments/assets/b1911590-8e0b-472b-bd64-f70c971d46a2)

After relaunching the app was immediately working.
Yesterday, when I've tried using Legcord for the first time, I was also stuck at a blank screen. After 4-5 relaunches it was actually working and I was able to login and connect to servers.

**Comment by ThaDaVos** [comment]
~I am having the same issue and checking the `devtools` it also shows `Equicord` failing to load - referencing `preload.mjs:20`~
EDIT: My bug is related to an coding error inside `Equicord` - there are two faulty if-checks - If I manually fix them and reload using `CTRL+R` it works again:
https://github.com/Equicord/Equicord/blob/9af91ed9fb1617dec085ebe3611148e7a3b5ebdd/src/plugins/fakeNitro/index.tsx#L34
https://github.com/Equicord/Equicord/blob/9af91ed9fb1617dec085ebe3611148e7a3b5ebdd/src/equicordplugins/statusPresets/index.tsx#L127C47-L127C50

Perhaps something like it is also happening with `Vencord` - maybe Legcord interferes with the loading of the plugins somehow

**Comment by thororen1234** [comment]
> ~I am having the same issue and checking the `devtools` it also shows `Equicord` failing to load - referencing `preload.mjs:20`~ EDIT: My bug is related to an coding error inside `Equicord` - there are two faulty if-checks - If I manually fix them and reload using `CTRL+R` it works again: https://github.com/Equicord/Equicord/blob/9af91ed9fb1617dec085ebe3611148e7a3b5ebdd/src/plugins/fakeNitro/index.tsx#L34 https://github.com/Equicord/Equicord/blob/9af91ed9fb1617dec085ebe3611148e7a3b5ebdd/src/equicordplugins/statusPresets/index.tsx#L127C47-L127C50
> 
> Perhaps something like it is also happening with `Vencord` - maybe Legcord interferes with the loading of the plugins somehow

For Equicord:
This was fixed my end was fine thats why it was pushed but apperantly others had issues so the ? check was added back

**Comment by sashapestrov** [comment]
> Deleting the cache in `~/Library/Application Support/legcord/Cache/Cache_Data` temporarily fixed the problem

Thank you, a lot - it really fixing the problem, lOl

**Comment by KarboXXX** [comment]
deleting `$HOME/.config/legcord/Code\ Cache` (on Debian) temporarily fixes the problem, allowing me to launch Legcord with Vencord only in the first launch, if i restart Legcord without deleting `Code Cache` Legcord simply does not load Vencord at all.

**Comment by smartfrigde** [comment]
Please try running Legcord with `DISABLE_V8_COMPILE_CACHE=1` environment value, this might fix the issue

**Comment by KarboXXX** [comment]
> Please try running Legcord with `DISABLE_V8_COMPILE_CACHE=1` environment value, this might fix the issue

Can confirm this really fixed the issue both for starting Legcord the first time, and restarting it. Thank you and sorry for the late reply.

**Comment by smartfrigde** [comment]
https://github.com/Legcord/Legcord/commit/9e0f61a750ade51e7c2bfe699fb989686858dfd1

I removed the library responsible for V8 caching; however, I can still reproduce the issue on my end, even after its removal.  

### Technical Background  
The problem occurs because Electron's preload script breaks on reloads—it loads too late (after Discord has already started loading), which disrupts client mod injection and some of our code.  

As a temporary fix introduced a few versions ago, I replaced the standard `CTRL+R` reload with [reloadIgnoringCache](https://www.electronjs.org/docs/latest/api/web-contents#contentsreloadignoringcache), which bypasses the Chromium cache. While this solution helps for now, permanently disabling the cache is not ideal.  

I’m currently unable to find what causes the issue, so I’m adding the appropriate GitHub **help wanted** tags, so hopefully it brings more attention to potential contributors.

**Comment by smartfrigde** [comment]
I'm happy to announce that this issue has been fixed with [this commit](https://github.com/Legcord/Legcord/commit/19625d3065b8afb863d84c9115a96b98693aa583)

After revisiting the Electron documentation for the hundredth time, I noticed an update to the ESM modules page. A few months ago, we transitioned the entire codebase—including the preload script—to ESM. At the time of the transition, the documentation did **not** mention that [unsandboxed ESM preload scripts run **after** the page loads if it contains no content](https://www.electronjs.org/docs/latest/tutorial/esm#unsandboxed-esm-preload-scripts-will-run-after-page-load-on-pages-with-no-content).  

This big detail was missing from the documentation when we made the switch, which led to the issue. I'll be starting a rewrite of the preload script soon to move back to ESM (cause I temporarily switched preload to CJS) but with sandboxing enabled, which should hopefully avoid similar problems in the future.
