### ISSUE TITLE
legcord appimage doesn't go past the loading screen and just get stuck on grey page

### ISSUE THREAD

**Issue by DaRandomCube** [smartfrigde/armcord#799]
**Describe the bug**
out of nowhere, i decided to open legcord, except it doesn't launch
as you see in the screenshot section, it's stuck there
and no, nothing was changed
sometimes, a popup appears about a javascript error thing 

**To Reproduce**
1. open legcord appimage
2. boom

**Expected behavior**
it works and i can use legcord to do whatever on discord

**Screenshots**
![image](https://github.com/user-attachments/assets/d526837c-928f-4429-806d-b792cc3c7831)
![image](https://github.com/user-attachments/assets/18899762-9d3e-4fe2-9f11-a0e57f83b436)

**Desktop (please complete the following information):**
 - OS: fedora 41 kde spin
 - Method of installation: appimage
 - Version: 1.0.5

**Additional context**
output of launching in terminal
```
Legcord has been run before. Skipping setup.
Wayland detected, using PipeWire for video capture.
Config is fine
Window config is fine
Performance mode enabled
[Mod Loader]: Downloading shelter...
[Config Manager] Current config: {
    "windowStyle": "native",
    "channel": "stable",
    "legcordCSP": true,
    "minimizeToTray": true,
    "keybinds": [],
    "audio": "loopbackWithMute",
    "multiInstance": false,
    "mods": [
        "equicord"
    ],
    "transparency": "none",
    "spellcheck": true,
    "hardwareAcceleration": true,
    "performanceMode": "performance",
    "skipSplash": false,
    "inviteWebsocket": true,
    "startMinimized": false,
    "tray": "dynamic",
    "disableHttpCache": false,
    "customJsBundle": "https://legcord.app/placeholder.js",
    "customCssBundle": "https://legcord.app/placeholder.css",
    "disableAutogain": false,
    "useLegacyCapturer": false,
    "mobileMode": false,
    "trayIcon": "dynamic",
    "doneSetup": true,
    "clientName": "Legcord",
    "customIcon": "/usr/share/legcord/app.asar/assets/desktop.png",
    "smoothScroll": true,
    "autoScroll": false,
    "modCache": {
        "shelter": "e8b719c3d7aef1add5926b66da7a6f65a9c6a400",
        "vencord": "88e8fa7e904e525c4c1110d057f0812e4008ff7c",
        "equicord": "b110b85eb592ae54f215ba33fd4db43f9e861d48"
    }
}
Setting up CSP unrestricter...
ATTENTION: default value of option mesa_glthread overridden by environment.
[Mod Loader]: Downloading equicord...
[Window state manager] {"width":1920,"height":1000,"isMaximized":false,"x":0,"y":36}
[Window state manager] {"width":1920,"height":1000,"isMaximized":false,"x":0,"y":36}
[Window state manager] {"width":1920,"height":1000,"isMaximized":false,"x":0,"y":36}
[Window state manager] {"width":1920,"height":1000,"isMaximized":false,"x":0,"y":36}
[Window state manager] {"width":1920,"height":1000,"isMaximized":false,"x":0,"y":36}
Starting screenshare module...
[arRPC > process] started
[arRPC > websocket] listening on 6463
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
(node:14952) UnhandledPromiseRejectionWarning: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ProcessServer.getDetectables (file:///tmp/.mount_legcormJemeF/resources/app.asar/node_modules/arrpc/src/process/index.js:108:20)
(Use `legcord --trace-warnings ...` to show where the warning was created)
(node:14952) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14952) UnhandledPromiseRejectionWarning: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ProcessServer.getDetectables (file:///tmp/.mount_legcormJemeF/resources/app.asar/node_modules/arrpc/src/process/index.js:108:20)
    at async ProcessServer.scan (file:///tmp/.mount_legcormJemeF/resources/app.asar/node_modules/arrpc/src/process/index.js:31:26)
(node:14952) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:14952) electron: Failed to load URL: https://discord.com/app with error: ERR_CONNECTION_REFUSED
[Theme Manager] Loaded Quick CSS
[14996:1206/171143.361300:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
(node:14952) UnhandledPromiseRejectionWarning: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ProcessServer.getDetectables (file:///tmp/.mount_legcormJemeF/resources/app.asar/node_modules/arrpc/src/process/index.js:108:20)
    at async ProcessServer.scan (file:///tmp/.mount_legcormJemeF/resources/app.asar/node_modules/arrpc/src/process/index.js:31:26)
(node:14952) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:14952) UnhandledPromiseRejectionWarning: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ProcessServer.getDetectables (file:///tmp/.mount_legcormJemeF/resources/app.asar/node_modules/arrpc/src/process/index.js:108:20)
    at async ProcessServer.scan (file:///tmp/.mount_legcormJemeF/resources/app.asar/node_modules/arrpc/src/process/index.js:31:26)
(node:14952) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[14996:1206/171151.308997:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[14996:1206/171153.244160:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
(node:14952) UnhandledPromiseRejectionWarning: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ProcessServer.getDetectables (file:///tmp/.mount_legcormJemeF/resources/app.asar/node_modules/arrpc/src/process/index.js:108:20)
    at async ProcessServer.scan (file:///tmp/.mount_legcormJemeF/resources/app.asar/node_modules/arrpc/src/process/index.js:31:26)
(node:14952) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```

**Comment by smartfrigde** [comment]
Can you reproduce this with https://github.com/Legcord/Legcord/releases/tag/v1.1.0?

**Comment by DaRandomCube** [comment]
Way too late, now on windows temporarily so i can't test
And iirc it was working before the partition went corrupt
Sorry for not being able to test and reproduce
